from tkinter import *
from tkinter import filedialog
from tkinter import messagebox
from jecommonsettings import *
from jelayers import *
from jetracks import *
from jevideosettings import *
from jevisualizerrunner import *
import configreader

class JEVisualizerGUI:
    def __init__(self, master, settings):
        self.master = master
        self.settings = settings
        master.title("JEVGUI")
        EW = 40

        self.header = Label(master, text="JEVisualizer GUI", font=("Times", 12, "bold"))
        self.header.grid(row=0, columnspan=2)
        self.subhead = Label(master, text="a simple GUI for creating JEVisalizer config files", font=("Courier", 10))
        self.subhead.grid(row=1, columnspan=2)

        self.left = Frame(master)
        self.left.grid(row=2, column=0, sticky=N)
        
        self.right = Frame(master)
        self.right.grid(row=2, column=1, sticky=N)   
     
        self.commonsettings_frame = Frame(self.left)
        self.commonsettings_frame.grid(row=0, column=0)

        self.videosettings_frame=Frame(self.left)
        self.videosettings_frame.grid(row=1, column=0)

        self.trackframe = Frame(self.right)
        self.trackframe.grid()

        self.layerframe = Frame(self.right)
        self.layerframe.grid()

        self.commonsettings = JECommonSettings(self, self.settings)
        self.commonsettings.view(self.commonsettings_frame)

        self.videosettings = JEVideoSettings(self, self.settings)
        self.videosettings.view(self.videosettings_frame)
    
        self.tracks = JETracks(self, self.settings)
        self.tracks.view(self.trackframe)

        self.layers = JELayers(self, self.settings)
        self.layers.view(self.layerframe)

        self.buttons = Frame(master)
        self.buttons.grid(row=4, column=0)

        self.config_button = Button(self.buttons, text="Load settings from config files", command=self.load_config)
        self.config_button.grid(row=0, column=0)
        self.config_button = Button(self.buttons, text="Create config files", command=self.create_config)
        self.config_button.grid(row=0, column=1)
        self.run_button = Button(self.buttons, text="Run JEVisualizer", command=self.run)
        self.run_button.grid(row=0, column=2)
        self.run_button = Button(self.buttons, text="Create config files and run JEVisualizer", command=self.create_and_run)
        self.run_button.grid(row=0, column=2)

        self.visualizer_runner = JEVisualizerRunner(self, self.master, self.settings)

    
    def getmediadir(self):
        return self.commonsettings.getmediadir()

    def replace_vars(self, s):
        return self.commonsettings.replace_vars(s)

    def create_config(self):
        path = self.commonsettings.get_config_path()
        ofilepath=self.commonsettings.get_ofile_path()
        ofilename=ofilepath+self.commonsettings.get_ofilename()
        
        main=open(path+"main.config", "w")
        main.write("/*\n * JEVisualizer config file generated by JEVisualizer GUI\n */\n\n")
        visualizer=open(path+"visualizer.config", "w")
        visualizer.write("/*\n * JEVisualizer config file generated by JEVisualizer GUI\n */\n\n")
        visualizer.write("OUTPUT-FILE=\""+ofilename+"\"\n")
        self.videosettings.write_config(visualizer)
        self.tracks.write_config(main, visualizer)
        self.layers.write_config(visualizer, path)

        oec = self.commonsettings.get_oec_command()
        #main.write("A-FREQUENCY=80\n")
        main.write("VISUALIZER=\""+path+"visualizer.config\"\n")
        main.write("ON-END=\""+oec+"\"\n")
        main.close()
        visualizer.close()
        messagebox.showinfo("JEVGUI: Config files created", "Config files created")

    def load_config(self):
        path = self.commonsettings.get_config_path()
        ofilepath=self.commonsettings.get_ofile_path()
        ofilename=ofilepath+self.commonsettings.get_ofilename()
        main=configreader.readConfigFromFile(path+"main.config")
        visualizer_file=path+"visualizer.config"
        oec=""
        for i in main:
            if i[0]==1 and i[1][0]=="VISUALIZER": visualizer_file=i[2]
            if i[0]==1 and i[1][0]=="ON-END": oec=i[2]
        visualizer=configreader.readConfigFromFile(visualizer_file)
        ofilename=""
        for i in visualizer:
            if i[0]==1 and i[1][0]=="OUTPUT-FILE": ofilename=i[2]
        self.commonsettings.set_oec_command(oec)
        self.commonsettings.set_ofilename(ofilename)
        
        self.videosettings.load_config(visualizer)
        self.tracks.load_config(main, visualizer)
        self.layers.load_config(visualizer)

    def run(self):
        command = self.commonsettings.get_jevisualizer_command()
        self.visualizer_runner.run_JEVisualizer(command)
        

    def create_and_run(self):
        self.create_config()
        self.run()


    
settingsf=open("default_variables")
t=settingsf.readlines()
settingsf.close()
settings={}
for l in t:
    if l[-1]=="\n": l=l[:-1]
    l=l.split("=")
    p=l[0]
    v="=".join(l[1:])
    settings[p]=v

root = Tk()
gui = JEVisualizerGUI(root, settings)
root.mainloop()
